export const FETCH_PHOTOS_BEGIN = "FETCH_PHOTOS_BEGIN";
export const FETCH_PHOTOS_SUCCESS =
  "FETCH_PHOTOS_SUCCESS";
export const FETCH_PHOTOS_FAILURE =
  "FETCH_PHOTOS_FAILURE";
export const TOGGLE_SELECTION = "TOGGLE_SELECTION";
export const TOGGLE_SELECT_ALL = "TOGGLE_SELECT_ALL";
export const SHARE_PHOTO_UPDATE = "SHARE_PHOTO_UPDATE";
export const SHARE_PHOTO_FAILURE = "SHARE_PHOTO_FAILURE";
export const SHARE_SELECTED_PHOTOS_FAILURE = "SHARE_SELECTED_PHOTOS_FAILURE";
export const WEBSOCKET_CONNECT = "WEBSOCKET_CONNECT";
export const WEBSOCKET_SEND = "WEBSOCKET_SEND";
export const WEBSOCKET_DISCONNECT = "WEBSOCKET_DISCONNECT";
export const WEBSOCKET_OPEN = "WEBSOCKET_OPEN";
export const WEBSOCKET_CLOSE = "WEBSOCKET_CLOSE";
export const WEBSOCKET_MESSAGE = "WEBSOCKET_MESSAGE";
export const PENDING_APPROVAL = "PENDING_APPROVAL";
export const WEBSITE_APPROVED = "WEBSITE_APPROVED";